### ISSUE TITLE
Does not work for placing only two blocks in rapid succession and places second and third blocks at the same time

### ISSUE THREAD

**Issue by Slooshie1** [Flourick/AccurateBlockPlacement#5]
I wasn't sure if this is intentional; it might be. This mod works somewhat fine but the second block doesn't place correctly. It waits for the third block to be placed (when the cursor is 2 blocks or more away from the original block) to place the second block, which causes the second and third block to be placed at the same time. This causes issues on servers with anti-cheats and it makes building more janky. A better example of it not working the way I wish it did, which is shown in the attached video, is that you cannot click-and-hold to place only two blocks in rapid succession, side by side. It will only place the first block.

https://user-images.githubusercontent.com/90230538/159868276-866232d0-7975-4ed6-88df-4872298315a3.mp4

**Comment by Flourick** [comment]
I did not make the logic of how this mod works I just maintain it and don't really have any intentions to change it in any way, just to keep it alive. However PRs are welcome if you want to contribute.
