### ISSUE TITLE
[Feature Request] Accurate block removal

### ISSUE THREAD

**Issue by Felix14-v2** [Flourick/AccurateBlockPlacement#7]
Compared to Bedrock Edition, Java lacks so much the ability to accurately remove block lines when moving. That is, the same thing that this mod already does, but instead of placing blocks, they should be removed when holding down the block destruction button.
Perhaps adding a new mode switch keybind would be a good idea.

**Comment by Flourick** [comment]
This is out of scope for this mod.

**Comment by Felix14-v2** [comment]
Are there any alternatives for this?

**Comment by Flourick** [comment]
My other mod [FVT](https://modrinth.com/mod/fvt) allows you to set the delay between breaking blocks in creative.
